name: C/C++ AppImage

on:
  push:
    branches: [ "main", "release-**"]
  pull_request:
    branches: [ "main" ]

jobs:
  build-appimage:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjsoncpp-dev
      - name: configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Releas
      - name: build
        run: cmake --build build
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@fe2205a4d6056be47051f7b1b3811106e9814910
        env:
          UPDATE_INFO: gh-releases-zsync|callfishxt|mtpc-cpp|latest|*x86_64.AppImage.zsync
        with:
          recipe: dev/AppImageBuilder.yml
      - uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: './*.AppImage*'
