name: CMake Build and AppImage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.25'

    - name: Install dependencies
      run: |
        wget https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        sudo mv appimagetool-x86_64.AppImage /usr/local/bin/appimagetool

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        cmake --build .
    - name: Build AppImage
      uses: AppImageCrafters/build-appimage-action@fe2205a4d6056be47051f7b1b3811106e9814910
      env:
        UPDATE_INFO: gh-releases-zsync|callfishxt|mtpc-cpp|latest|*x86_64.AppImage.zsync
      with:
        recipe: dev/AppImageBuilder.yml
        
    - uses: actions/upload-artifact@v4
      with:
        name: AppImage
        path: './*.AppImage*'
