name: CMake Build and AppImage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.25'

    - name: Install dependencies
      run: sudo apt-get install -y libjsoncpp-dev appimagetool

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        cmake --build .

    - name: Create AppImage
      run: |
        mkdir -p AppDir/usr/bin
        cp build/mtpc AppDir/usr/bin/
        # Create a simple AppImage metadata file
        echo "[Desktop Entry]" > AppDir/mtpc.desktop
        echo "Name=mtpc" >> AppDir/mtpc.desktop
        echo "Exec=mtpc" >> AppDir/mtpc.desktop
        echo "Icon=mtpc" >> AppDir/mtpc.desktop
        echo "Type=Application" >> AppDir/mtpc.desktop
        echo "Categories=Utility;" >> AppDir/mtpc.desktop
        # Copy an icon if you have one (optional)
        # cp path/to/icon.png AppDir/mtpc.png
        # Create the AppImage
        appimagetool AppDir mtpc.AppImage

    - name: Upload AppImage
      uses: actions/upload-artifact@v3
      with:
        name: mtpc-appimage
        path: mtpc.AppImage
