name: Windows Build x86_64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.25'

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        cmake --build .
        mkdir app
        cd ..
        copy build\mtpc build\app\mtpc
        copy packs.json build\app\packs.json
        copy config.sff build\app\config.sff
        
    - uses: actions/upload-artifact@v4
      with:
        name: mtpc
        path: 'build/app/*'
